---
title: "Weather Underground GDD"
author: "Kate Davis"
date: "09/29/2015"
output: html_document
---
```{r setup}
require(RCurl)
require(lubridate)
```
```{r monthly}
wmurl="http://api.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KMEPARSO2&day=1&month=1&year=2009&dayend=29&monthend=9&yearend=2015&graphspan=custom&format=1"
wum=read.csv(wmurl,stringsAsFactors = F,na.strings="<br>",blank.lines.skip = T,row.names=NULL)
wum=wum[!is.na(wum$Date),]
wum$Date=as.Date(wum$Date)
saveRDS(wum,"wum.rds")
```


```{r daily}
fwdurl="http://api.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KMEPARSO2&day=%d&month=%d&year=%d&graphspan=day&format=1"
dvec=wum$Date #seq(as.Date("2009-05-15"), as.Date("2015-09-28"), by="days")
wdurl=sprintf(fwdurl,day(dvec),month(dvec),year(dvec))
gweather<-function(wdurl){
  dd=read.csv(wdurl,stringsAsFactors = F,na.strings="<br>",blank.lines.skip = T,row.names=NULL)
  dd=dd[!is.na(dd$row.names),]
  cn=names(dd)
  cn=cn[2:length(cn)]
  dd=dd[,1:(ncol(dd)-1)]
  names(dd)=cn
  return(dd)
}
dd=sapply(wdurl,gweather)
ww <- do.call("rbind", dd)
saveRDS(ww,"ww.rds")
```

